from __future__ import annotations

import typing as t

# Span attributes

SPAN_NAMESPACE = "dreadnode"

SpanType = t.Literal["run", "task", "span", "run_update"]

SPAN_ATTRIBUTE_TYPE = f"{SPAN_NAMESPACE}.type"
SPAN_ATTRIBUTE_SCHEMA = f"{SPAN_NAMESPACE}.schema"
SPAN_ATTRIBUTE_KIND = f"{SPAN_NAMESPACE}.kind"
SPAN_ATTRIBUTE_TAGS_ = f"{SPAN_NAMESPACE}.tags"
SPAN_ATTRIBUTE_KIND = f"{SPAN_NAMESPACE}.kind"
SPAN_ATTRIBUTE_PROJECT = f"{SPAN_NAMESPACE}.project"

SPAN_ATTRIBUTE_RUN_ID = f"{SPAN_NAMESPACE}.run.id"

SPAN_ATTRIBUTE_RUN_PARAMS = f"{SPAN_NAMESPACE}.run.params"
SPAN_ATTRIBUTES_RUN_INPUTS = f"{SPAN_NAMESPACE}.run.inputs"
SPAN_ATTRIBUTE_RUN_METRICS = f"{SPAN_NAMESPACE}.run.metrics"
SPAN_ATTRIBUTE_RUN_ARTIFACTS = f"{SPAN_NAMESPACE}.run.artifacts"

SPAN_ATTRIBUTE_PARENT_TASK_ID = f"{SPAN_NAMESPACE}.task.parent_id"

SPAN_ATTRIBUTE_TASK_KEY = f"{SPAN_NAMESPACE}.task.key"
SPAN_ATTRIBUTE_TASK_PARAMS = f"{SPAN_NAMESPACE}.task.params"
SPAN_ATTRIBUTE_TASK_INPUTS = f"{SPAN_NAMESPACE}.task.inputs"
SPAN_ATTRIBUTE_TASK_METRICS = f"{SPAN_NAMESPACE}.task.metrics"
SPAN_ATTRIBUTE_TASK_OUTPUT = f"{SPAN_NAMESPACE}.task.output"

SPAN_ATTRIBUTE_TASK_ARGS = f"{SPAN_NAMESPACE}.task.args"  # deprecated
SPAN_ATTRIBUTE_TASK_SCORES = f"{SPAN_NAMESPACE}.task.scores"  # deprecated

# Environment variable names

ENV_SERVER_URL = "DREADNODE_SERVER_URL"
ENV_SERVER = "DREADNODE_SERVER"  # alternative to SERVER_URL
ENV_API_TOKEN = "DREADNODE_API_TOKEN"  # noqa: S105
ENV_API_KEY = "DREADNODE_API_KEY"  # alternative to API_TOKEN
ENV_LOCAL_DIR = "DREADNODE_LOCAL_DIR"
ENV_PROJECT = "DREADNODE_PROJECT"

# Default values

DEFAULT_SERVER_URL = "https://platform.dreadnode.io"
