from __future__ import annotations

import typing as t

SPAN_NAMESPACE = "dreadnode"

SpanType = t.Literal["run", "task", "span", "run_update"]

SPAN_ATTRIBUTE_TYPE_KEY = f"{SPAN_NAMESPACE}.type"
SPAN_ATTRIBUTE_SCHEMA_KEY = f"{SPAN_NAMESPACE}.schema"
SPAN_ATTRIBUTE_TAGS_KEY = f"{SPAN_NAMESPACE}.tags"
SPAN_ATTRIBUTE_KIND_KEY = f"{SPAN_NAMESPACE}.kind"

SPAN_ATTRIBUTE_RUN_ID_KEY = f"{SPAN_NAMESPACE}.run.id"
SPAN_ATTRIBUTE_RUN_METRICS_KEY = f"{SPAN_NAMESPACE}.run.metrics"
SPAN_ATTRIBUTE_RUN_PARAMS_KEY = f"{SPAN_NAMESPACE}.run.params"

SPAN_ATTRIBUTE_PARENT_TASK_ID_KEY = f"{SPAN_NAMESPACE}.task.parent_id"
SPAN_ATTRIBUTE_TASK_ARGS_KEY = f"{SPAN_NAMESPACE}.task.args"
SPAN_ATTRIBUTE_TASK_OUTPUT_KEY = f"{SPAN_NAMESPACE}.task.output"
SPAN_ATTRIBUTE_TASK_SCORES_KEY = f"{SPAN_NAMESPACE}.task.scores"
