from __future__ import annotations

import typing as t

# Span attributes

SPAN_NAMESPACE = "dreadnode"

SpanType = t.Literal["run", "task", "span", "run_update"]

SPAN_ATTRIBUTE_TYPE_KEY = f"{SPAN_NAMESPACE}.type"
SPAN_ATTRIBUTE_SCHEMA_KEY = f"{SPAN_NAMESPACE}.schema"
SPAN_ATTRIBUTE_TAGS_KEY = f"{SPAN_NAMESPACE}.tags"
SPAN_ATTRIBUTE_KIND_KEY = f"{SPAN_NAMESPACE}.kind"
SPAN_ATTRIBUTE_PROJECT_KEY = f"{SPAN_NAMESPACE}.project"

SPAN_ATTRIBUTE_RUN_ID_KEY = f"{SPAN_NAMESPACE}.run.id"

SPAN_ATTRIBUTE_RUN_PARAMS_KEY = f"{SPAN_NAMESPACE}.run.params"
SPAN_ATTRIBUTES_RUN_INPUTS_KEY = f"{SPAN_NAMESPACE}.run.inputs"
SPAN_ATTRIBUTE_RUN_METRICS_KEY = f"{SPAN_NAMESPACE}.run.metrics"
SPAN_ATTRIBUTE_RUN_ARTIFACTS_KEY = f"{SPAN_NAMESPACE}.run.artifacts"

SPAN_ATTRIBUTE_PARENT_TASK_ID_KEY = f"{SPAN_NAMESPACE}.task.parent_id"

SPAN_ATTRIBUTE_TASK_PARAMS_KEY = f"{SPAN_NAMESPACE}.task.params"
SPAN_ATTRIBUTE_TASK_INPUTS_KEY = f"{SPAN_NAMESPACE}.task.inputs"
SPAN_ATTRIBUTE_TASK_METRICS_KEY = f"{SPAN_NAMESPACE}.task.metrics"
SPAN_ATTRIBUTE_TASK_OUTPUT_KEY = f"{SPAN_NAMESPACE}.task.output"

SPAN_ATTRIBUTE_TASK_ARGS_KEY = f"{SPAN_NAMESPACE}.task.args"  # deprecated
SPAN_ATTRIBUTE_TASK_SCORES_KEY = f"{SPAN_NAMESPACE}.task.scores"  # deprecated

# Environment variable names

ENV_SERVER_URL = "DREADNODE_SERVER_URL"
ENV_SERVER = "DREADNODE_SERVER"  # alternative to SERVER_URL
ENV_API_TOKEN = "DREADNODE_API_TOKEN"
ENV_API_KEY = "DREADNODE_API_KEY"  # alternative to API_TOKEN
ENV_LOCAL_DIR = "DREADNODE_LOCAL_DIR"
ENV_PROJECT = "DREADNODE_PROJECT"
