from dreadnode.scorers.base import (
    Scorer,
    ScorerCallable,
    ScorerLike,
    ScorerResult,
    ScorersLike,
    ScorerWarning,
    add,
    and_,
    avg,
    clip,
    equals,
    invert,
    normalize,
    not_,
    or_,
    remap_range,
    scale,
    subtract,
    threshold,
    weighted_avg,
)
from dreadnode.scorers.classification import detect_refusal_with_zero_shot, zero_shot_classification
from dreadnode.scorers.consistency import character_consistency
from dreadnode.scorers.contains import (
    contains,
    detect_ansi_escapes,
    detect_bias,
    detect_refusal,
    detect_sensitive_keywords,
    detect_unsafe_shell_content,
)
from dreadnode.scorers.crucible import contains_crucible_flag
from dreadnode.scorers.format import is_json, is_xml
from dreadnode.scorers.harm import detect_harm_with_openai
from dreadnode.scorers.judge import llm_judge
from dreadnode.scorers.length import length_in_range, length_ratio, length_target
from dreadnode.scorers.lexical import type_token_ratio
from dreadnode.scorers.pii import detect_pii, detect_pii_with_presidio
from dreadnode.scorers.readability import readability
from dreadnode.scorers.rigging import wrap_chat
from dreadnode.scorers.sentiment import sentiment, sentiment_with_perspective
from dreadnode.scorers.similarity import (
    bleu,
    similarity,
    similarity_with_litellm,
    similarity_with_sentence_transformers,
    similarity_with_tf_idf,
)

__all__ = [
    "Scorer",
    "ScorerCallable",
    "ScorerLike",
    "ScorerResult",
    "ScorerResult",
    "ScorerWarning",
    "ScorersLike",
    "add",
    "and_",
    "avg",
    "bleu",
    "character_consistency",
    "character_consistency",
    "clip",
    "contains",
    "contains_crucible_flag",
    "detect_ansi_escapes",
    "detect_ansi_escapes",
    "detect_bias",
    "detect_bias",
    "detect_harm_with_openai",
    "detect_pii",
    "detect_pii_with_presidio",
    "detect_pii_with_presidio",
    "detect_refusal",
    "detect_refusal_with_zero_shot",
    "detect_refusal_with_zero_shot",
    "detect_sensitive_keywords",
    "detect_sensitive_keywords",
    "detect_unsafe_shell_content",
    "detect_unsafe_shell_content",
    "equals",
    "invert",
    "is_json",
    "is_xml",
    "length_in_range",
    "length_ratio",
    "length_target",
    "llm_judge",
    "llm_judge",
    "normalize",
    "not_",
    "or_",
    "readability",
    "remap_range",
    "scale",
    "sentiment",
    "sentiment_with_perspective",
    "similarity",
    "similarity_with_litellm",
    "similarity_with_sentence_transformers",
    "similarity_with_tf_idf",
    "subtract",
    "threshold",
    "type_token_ratio",
    "weighted_avg",
    "wrap_chat",
    "wrap_chat",
    "zero_shot_classification",
]
