import typing as t

SPAN_NAMESPACE = "dreadnode"

# === Span Types ===
SpanType = t.Literal[
    "run",
    "task",
    "evaluation",
    "agent",
    "study",
    "tool",
    "span",
    "run_update",
    "run_fragment",
    "generation",  # LLM generation step
    "scorer",  # Scorer execution
    "trial",  # Optimization trial
]

# === Generic Span Attributes (all spans) ===
SPAN_ATTRIBUTE_VERSION = f"{SPAN_NAMESPACE}.version"
SPAN_ATTRIBUTE_TYPE = f"{SPAN_NAMESPACE}.type"
SPAN_ATTRIBUTE_SCHEMA = f"{SPAN_NAMESPACE}.schema"
SPAN_ATTRIBUTE_LABEL = f"{SPAN_NAMESPACE}.label"
SPAN_ATTRIBUTE_TAGS_ = f"{SPAN_NAMESPACE}.tags"
SPAN_ATTRIBUTE_PROJECT = f"{SPAN_NAMESPACE}.project"
SPAN_ATTRIBUTE_PARAMS = f"{SPAN_NAMESPACE}.params"
SPAN_ATTRIBUTE_INPUTS = f"{SPAN_NAMESPACE}.inputs"
SPAN_ATTRIBUTE_METRICS = f"{SPAN_NAMESPACE}.metrics"
SPAN_ATTRIBUTE_OUTPUTS = f"{SPAN_NAMESPACE}.outputs"
SPAN_ATTRIBUTE_OBJECTS = f"{SPAN_NAMESPACE}.objects"
SPAN_ATTRIBUTE_OBJECT_SCHEMAS = f"{SPAN_NAMESPACE}.object_schemas"
SPAN_ATTRIBUTE_ARTIFACTS = f"{SPAN_NAMESPACE}.artifacts"
SPAN_ATTRIBUTE_RUN_ID = f"{SPAN_NAMESPACE}.run.id"
SPAN_ATTRIBUTE_PARENT_TASK_ID = f"{SPAN_NAMESPACE}.task.parent_id"
SPAN_ATTRIBUTE_LARGE_ATTRIBUTES = f"{SPAN_NAMESPACE}.large_attributes"

# === Generation Span Attributes ===
GENERATION_NAMESPACE = f"{SPAN_NAMESPACE}.generation"
GENERATION_ATTRIBUTE_MODEL = f"{GENERATION_NAMESPACE}.model"
GENERATION_ATTRIBUTE_INPUT_TOKENS = f"{GENERATION_NAMESPACE}.input_tokens"
GENERATION_ATTRIBUTE_OUTPUT_TOKENS = f"{GENERATION_NAMESPACE}.output_tokens"
GENERATION_ATTRIBUTE_TOTAL_TOKENS = f"{GENERATION_NAMESPACE}.total_tokens"
GENERATION_ATTRIBUTE_CONTENT = f"{GENERATION_NAMESPACE}.content"
GENERATION_ATTRIBUTE_ROLE = f"{GENERATION_NAMESPACE}.role"
GENERATION_ATTRIBUTE_TOOL_CALLS = f"{GENERATION_NAMESPACE}.tool_calls"
GENERATION_ATTRIBUTE_STOP_REASON = f"{GENERATION_NAMESPACE}.stop_reason"
GENERATION_ATTRIBUTE_FAILED = f"{GENERATION_NAMESPACE}.failed"
GENERATION_ATTRIBUTE_EXTRA = f"{GENERATION_NAMESPACE}.extra"

# === Tool Span Attributes ===
TOOL_NAMESPACE = f"{SPAN_NAMESPACE}.tool"
TOOL_ATTRIBUTE_NAME = f"{TOOL_NAMESPACE}.name"
TOOL_ATTRIBUTE_CALL_ID = f"{TOOL_NAMESPACE}.call_id"
TOOL_ATTRIBUTE_ARGUMENTS = f"{TOOL_NAMESPACE}.arguments"
TOOL_ATTRIBUTE_RESULT = f"{TOOL_NAMESPACE}.result"
TOOL_ATTRIBUTE_ERROR = f"{TOOL_NAMESPACE}.error"
TOOL_ATTRIBUTE_STOPPED = f"{TOOL_NAMESPACE}.stopped"

# === Scorer Span Attributes ===
SCORER_NAMESPACE = f"{SPAN_NAMESPACE}.scorer"
SCORER_ATTRIBUTE_NAME = f"{SCORER_NAMESPACE}.name"
SCORER_ATTRIBUTE_SCORE = f"{SCORER_NAMESPACE}.score"
SCORER_ATTRIBUTE_PASSED = f"{SCORER_NAMESPACE}.passed"
SCORER_ATTRIBUTE_RATIONALE = f"{SCORER_NAMESPACE}.rationale"
SCORER_ATTRIBUTE_STEP = f"{SCORER_NAMESPACE}.step"

# === Trial Span Attributes ===
TRIAL_NAMESPACE = f"{SPAN_NAMESPACE}.trial"
TRIAL_ATTRIBUTE_ID = f"{TRIAL_NAMESPACE}.id"
TRIAL_ATTRIBUTE_STEP = f"{TRIAL_NAMESPACE}.step"
TRIAL_ATTRIBUTE_CANDIDATE = f"{TRIAL_NAMESPACE}.candidate"
TRIAL_ATTRIBUTE_STATUS = f"{TRIAL_NAMESPACE}.status"
TRIAL_ATTRIBUTE_SCORES = f"{TRIAL_NAMESPACE}.scores"
TRIAL_ATTRIBUTE_IS_PROBE = f"{TRIAL_NAMESPACE}.is_probe"

# === Agent Span Attributes ===
AGENT_NAMESPACE = f"{SPAN_NAMESPACE}.agent"
AGENT_ATTRIBUTE_ID = f"{AGENT_NAMESPACE}.id"
AGENT_ATTRIBUTE_SESSION_ID = f"{AGENT_NAMESPACE}.session_id"
AGENT_ATTRIBUTE_TRAJECTORY = f"{AGENT_NAMESPACE}.trajectory"
AGENT_ATTRIBUTE_SCORES = f"{AGENT_NAMESPACE}.scores"

# === Evaluation Span Attributes ===
EVALUATION_NAMESPACE = f"{SPAN_NAMESPACE}.evaluation"
EVALUATION_ATTRIBUTE_TASK_NAME = f"{EVALUATION_NAMESPACE}.task_name"
EVALUATION_ATTRIBUTE_DATASET_SIZE = f"{EVALUATION_NAMESPACE}.dataset_size"
EVALUATION_ATTRIBUTE_ITERATIONS = f"{EVALUATION_NAMESPACE}.iterations"

# === Study Span Attributes ===
STUDY_NAMESPACE = f"{SPAN_NAMESPACE}.study"
STUDY_ATTRIBUTE_SEARCH_STRATEGY = f"{STUDY_NAMESPACE}.search_strategy"
STUDY_ATTRIBUTE_OBJECTIVES = f"{STUDY_NAMESPACE}.objectives"
STUDY_ATTRIBUTE_MAX_TRIALS = f"{STUDY_NAMESPACE}.max_trials"

# === Event Names ===
EVENT_NAME_OBJECT = f"{SPAN_NAMESPACE}.object"
EVENT_NAME_OBJECT_INPUT = f"{SPAN_NAMESPACE}.object.input"
EVENT_NAME_OBJECT_OUTPUT = f"{SPAN_NAMESPACE}.object.output"
EVENT_NAME_OBJECT_METRIC = f"{SPAN_NAMESPACE}.object.metric"
EVENT_NAME_OBJECT_LINK = f"{SPAN_NAMESPACE}.object.link"

# === Event Attributes ===
EVENT_ATTRIBUTE_OBJECT_LABEL = f"{SPAN_NAMESPACE}.object.label"
EVENT_ATTRIBUTE_OBJECT_HASH = f"{SPAN_NAMESPACE}.object.hash"
EVENT_ATTRIBUTE_LINK_HASH = f"{SPAN_NAMESPACE}.link.hash"
EVENT_ATTRIBUTE_ORIGIN_SPAN_ID = f"{SPAN_NAMESPACE}.origin.span_id"

# === Metric Attributes ===
METRIC_ATTRIBUTE_SOURCE_HASH = f"{SPAN_NAMESPACE}.origin.hash"
