---
name: Trigger Docs Update

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".hooks/generate_docs.py"
      - ".github/workflows/docs-update.yaml"
  workflow_dispatch:

jobs:
  notify-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.UPDATE_DOCS_APP_ID }}
          private-key: ${{ secrets.UPDATE_DOCS_PRIVATE_KEY }}
          owner: "${{ github.repository_owner }}"
          repositories: |
            docs

      - name: Trigger docs repository workflow
        uses: peter-evans/repository-dispatch@5fc4efd1a4797ddb68ffd0714a238564e4cc0e6f # v4.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: dreadnode/docs
          event-type: docs-update
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref_name }}",
              "sha": "${{ github.sha }}",
              "source_dir": "docs",
              "target_dir": "strikes",
              "nav_target": "Documentation/Strikes"
            }
