---
name: Tests

on:
  merge_group:
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "poetry.lock"
      - "uv.lock"
  pull_request:
    branches: [main]

jobs:
  python:
    name: Python - Lint, Typecheck, Test

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Install uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      with:
        version: "latest"
        python-version: ${{ matrix.python-version }}

    - name: Sync packages
      run: uv sync --all-extras

    - name: Format
      run: uv run ruff format --check .

    - name: Lint
      if: always()
      run: uv run ruff check --output-format=github .

    - name: Typecheck
      if: always()
      run: uv run mypy .

    - name: Test
      if: always()
      run: uv run pytest
